version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.5-stretch

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --prefer-dist --optimize-autoloader
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          when: always
          paths:
            - vendor

      - run: ./vendor/bin/phpunit
