version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-stretch

    steps:
      - checkout

      - run: sudo apt update
      # - run: sudo docker-php-ext-install zip

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: COMPOSER_MEMORY_LIMIT=-1 composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - run: ./vendor/bin/phpunit
